<template>
    <AppPage title="菜谱" subtitle="创建和查看结构化菜谱">
        <view class="surface-card section">
            <text class="section-title">新增菜谱</text><input v-model="form.name" class="field" placeholder="菜谱名称"><input v-model="form.baseServings" class="field" type="number" placeholder="基础份数"><input v-model="form.estimatedMinutes" class="field" type="number" placeholder="预计分钟数">
            <text class="subheading">食材</text><view v-for="(row,index) in form.ingredients" :key="index" class="ingredient-row"><picker :range="ingredientNames" @change="selectIngredient(index,$event)"><view class="picker-field">{{ ingredientName(row.ingredientId) }}</view></picker><input v-model="row.amount" class="field compact" type="digit" placeholder="用量"><picker :range="units" @change="selectUnit(index,$event)"><view class="picker-field compact">{{ row.unit }}</view></picker><button class="small-button" @click="removeIngredient(index)">移除</button></view>
            <button class="secondary-button" @click="addIngredient">添加食材</button><text class="subheading">步骤</text><view v-for="(step,index) in form.steps" :key="index" class="step-row"><text class="step-index">{{ index + 1 }}</text><input v-model="form.steps[index]" class="field" placeholder="烹饪步骤"><button class="small-button" @click="removeStep(index)">移除</button></view><button class="secondary-button" @click="addStep">添加步骤</button><button class="primary-button" :disabled="submitting" @click="submit">{{ submitting ? "提交中…" : "创建菜谱" }}</button><text v-if="feedback" class="feedback">{{ feedback }}</text>
        </view>
        <view class="surface-card section"><view class="section-heading"><text class="section-title">菜谱目录</text><button class="small-button" @click="load">刷新</button></view><AsyncStateView :loading="loading" :error="error" :empty="!loading && !error && recipes.length === 0" empty-title="暂无菜谱" empty-message="创建第一个结构化菜谱" @retry="load"><view v-for="recipe in recipes" :key="recipe.id" class="recipe-card"><text class="recipe-title">{{ recipe.name }}</text><text class="row-detail">{{ recipe.baseServings }} 份 · {{ recipe.estimatedMinutes }} 分钟</text><text class="subheading">食材</text><text v-for="item in recipe.ingredients" :key="`${recipe.id}-${item.position}`" class="row-detail">{{ ingredientName(item.ingredientId) }}：{{ String(item.amount) }} {{ item.unit }}</text><text class="subheading">步骤</text><text v-for="step in recipe.steps" :key="`${recipe.id}-step-${step.position}`" class="row-detail">{{ step.position }}. {{ step.instruction }}</text></view></AsyncStateView></view>
    </AppPage>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue"; import AppPage from "@/components/AppPage.vue"; import AsyncStateView from "@/components/AsyncStateView.vue"; import { createRecipe, listRecipes, type Recipe } from "@/api/recipes"; import type { InventoryUnit } from "@/api/inventory"; import { useIngredientStore } from "@/stores/ingredients"; import { toRecipeRequest, type RecipeFormState } from "@/forms/recipe-form";
const ingredientStore=useIngredientStore(); const recipes=ref<Recipe[]>([]); const loading=ref(false); const error=ref<string|null>(null); const submitting=ref(false); const feedback=ref(""); const units:InventoryUnit[]=["g","kg","ml","l","piece"]; const form=reactive<RecipeFormState>({name:"",baseServings:"",estimatedMinutes:"",ingredients:[{ingredientId:null,amount:"",unit:"g"}],steps:[""]}); const ingredientNames=computed(()=>ingredientStore.items.map((item)=>item.name));
function ingredientName(id:number|null):string{return id===null?"选择食材":ingredientStore.items.find((item)=>item.id===id)?.name??`食材 #${id}`;} function readable(value:unknown):string{return value instanceof Error?value.message:"操作失败，请稍后重试";} async function load():Promise<void>{loading.value=true;error.value=null;try{recipes.value=await listRecipes();}catch(e:unknown){error.value=readable(e);}finally{loading.value=false;}} function addIngredient():void{form.ingredients.push({ingredientId:null,amount:"",unit:"g"});} function removeIngredient(index:number):void{if(form.ingredients.length>1)form.ingredients.splice(index,1);} function addStep():void{form.steps.push("");} function removeStep(index:number):void{if(form.steps.length>1)form.steps.splice(index,1);} function selectIngredient(index:number,event:{detail:{value:number}}):void{form.ingredients[index]!.ingredientId=ingredientStore.items[event.detail.value]?.id??null;} function selectUnit(index:number,event:{detail:{value:number}}):void{form.ingredients[index]!.unit=units[event.detail.value]??"g";} function reset():void{form.name="";form.baseServings="";form.estimatedMinutes="";form.ingredients.splice(0,form.ingredients.length,{ingredientId:null,amount:"",unit:"g"});form.steps.splice(0,form.steps.length,"");} async function submit():Promise<void>{if(submitting.value)return;submitting.value=true;feedback.value="";try{await createRecipe(toRecipeRequest(form));reset();feedback.value="菜谱已创建";await load();}catch(e:unknown){feedback.value=readable(e);}finally{submitting.value=false;}} onMounted(async()=>{try{await ingredientStore.load();}catch{/* store state */}await load();});
</script>
<style scoped lang="scss">
.section{display:flex;flex-direction:column;gap:$space-md;margin-bottom:$space-lg}.section-heading{display:flex;align-items:center;justify-content:space-between;gap:$space-sm}.section-title,.recipe-title{font-size:$text-lg;font-weight:650}.subheading{font-weight:600;margin-top:$space-sm}.field,.picker-field{width:100%;min-height:78rpx;padding:0 $space-sm;border:2rpx solid $color-border;border-radius:$radius-sm;background:#fff;font-size:$text-md;line-height:78rpx}.ingredient-row{display:grid;grid-template-columns:minmax(0,1fr) minmax(110rpx,.65fr);gap:$space-sm;min-width:0}.ingredient-row .picker-field{min-width:0}.compact{min-width:0}.ingredient-row .small-button{grid-column:2;grid-row:2}.step-row{display:flex;align-items:center;gap:$space-sm}.step-index{width:40rpx;color:$color-text-secondary}.primary-button,.secondary-button,.small-button{min-height:76rpx;border-radius:$radius-sm;font-size:$text-md}.primary-button{background:$color-primary;color:#fff}.secondary-button,.small-button{background:$color-surface;color:$color-primary;border:2rpx solid $color-border}.small-button{min-height:58rpx;padding:0 $space-sm;font-size:$text-sm}.recipe-card{display:flex;flex-direction:column;gap:$space-xs;padding:$space-md 0;border-bottom:1rpx solid $color-border}.row-detail,.feedback{color:$color-text-secondary;line-height:1.55;overflow-wrap:anywhere}@media (min-width:600px){.ingredient-row{display:flex;align-items:center}.ingredient-row .picker-field{min-width:220rpx}.ingredient-row .small-button{grid-column:auto;grid-row:auto}.compact{flex:1;min-width:110rpx}}
</style>
