package com.xuhang.mealops.mealplan.api;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.util.UUID; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.context.annotation.Import; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.*; import org.springframework.test.web.servlet.setup.MockMvcBuilders; import org.springframework.web.context.WebApplicationContext; import com.jayway.jsonpath.JsonPath; import com.xuhang.mealops.support.PostgresTestConfiguration;

@SpringBootTest @Import(PostgresTestConfiguration.class)
class MealPlanApiIT {
 @Autowired WebApplicationContext context; MockMvc mvc; @BeforeEach void setup(){mvc=MockMvcBuilders.webAppContextSetup(context).build();}
 private long recipe() throws Exception {var i=mvc.perform(post("/api/v1/ingredients").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"MealIt"+UUID.randomUUID()+"\"}" )).andExpect(status().isCreated()).andReturn();long iid=((Number)JsonPath.read(i.getResponse().getContentAsString(),"$.id")).longValue();var r=mvc.perform(post("/api/v1/recipes").contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Recipe"+UUID.randomUUID()+"\",\"baseServings\":1,\"estimatedMinutes\":10,\"ingredients\":[{\"ingredientId\":"+iid+",\"amount\":100,\"unit\":\"g\"}],\"steps\":[\"cook\"]}" )).andExpect(status().isCreated()).andReturn();return ((Number)JsonPath.read(r.getResponse().getContentAsString(),"$.id")).longValue();}
 private String body(long recipe, boolean assigned){return "{\"startDate\":\"2026-08-05\",\"endDate\":\"2026-08-06\",\"slots\":[{\"date\":\"2026-08-05\",\"mealType\":\"DINNER\",\"recipeSelection\":"+(assigned?"{\"recipeId\":"+recipe+",\"targetServings\":1}":"null")+"},{\"date\":\"2026-08-06\",\"mealType\":\"LUNCH\",\"recipeSelection\":null}]}";}
 @Test void createGetConfirmAndCancelLifecycle() throws Exception {long r=recipe();var created=mvc.perform(post("/api/v1/meal-plans").contentType(MediaType.APPLICATION_JSON).content(body(r,true))).andExpect(status().isCreated()).andExpect(header().string("Location",org.hamcrest.Matchers.matchesPattern("/api/v1/meal-plans/[0-9]+"))).andExpect(jsonPath("$.status").value("DRAFT")).andReturn();long id=((Number)JsonPath.read(created.getResponse().getContentAsString(),"$.id")).longValue();mvc.perform(post("/api/v1/meal-plans/"+id+"/confirm")).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("MEAL_PLAN_INCOMPLETE"));mvc.perform(post("/api/v1/meal-plans/"+id+"/cancel")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("CANCELLED"));mvc.perform(put("/api/v1/meal-plans/"+id).contentType(MediaType.APPLICATION_JSON).content(body(r,true))).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("MEAL_PLAN_STATE_CONFLICT"));}
 @Test void completePlanConfirmsAndRejectsFurtherConfirm(){long r;try{r=recipe();var c=mvc.perform(post("/api/v1/meal-plans").contentType(MediaType.APPLICATION_JSON).content(body(r,true))).andExpect(status().isCreated()).andReturn();long id=((Number)JsonPath.read(c.getResponse().getContentAsString(),"$.id")).longValue();String full=body(r,true).replace(",\"recipeSelection\":null}",",\"recipeSelection\":{\"recipeId\":"+r+",\"targetServings\":1}}");mvc.perform(put("/api/v1/meal-plans/"+id).contentType(MediaType.APPLICATION_JSON).content(full)).andExpect(status().isOk());mvc.perform(post("/api/v1/meal-plans/"+id+"/confirm")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("CONFIRMED"));mvc.perform(post("/api/v1/meal-plans/"+id+"/confirm")).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("MEAL_PLAN_STATE_CONFLICT"));}catch(Exception e){throw new RuntimeException(e);}}
 @Test void missingPlanAndInvalidRequestAreProblemDetails() throws Exception {mvc.perform(get("/api/v1/meal-plans/999999999")).andExpect(status().isNotFound()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON)).andExpect(jsonPath("$.code").value("MEAL_PLAN_NOT_FOUND"));mvc.perform(post("/api/v1/meal-plans").contentType(MediaType.APPLICATION_JSON).content("{\"startDate\":\"2026-08-01\",\"endDate\":\"2026-08-04\",\"slots\":[]}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("VALIDATION_FAILED"));}
 @Test void nestedSelectionValidationReturnsProblemDetails() throws Exception {String prefix="{\"startDate\":\"2026-08-05\",\"endDate\":\"2026-08-05\",\"slots\":[{\"date\":\"2026-08-05\",\"mealType\":\"DINNER\",\"recipeSelection\":";for(String selection:new String[]{"{}","{\"targetServings\":1}","{\"recipeId\":1}","{\"recipeId\":null,\"targetServings\":1}","{\"recipeId\":1,\"targetServings\":null}","{\"recipeId\":0,\"targetServings\":1}","{\"recipeId\":-1,\"targetServings\":1}","{\"recipeId\":1,\"targetServings\":0}","{\"recipeId\":1,\"targetServings\":-1}"}){mvc.perform(post("/api/v1/meal-plans").contentType(MediaType.APPLICATION_JSON).content(prefix+selection+"}]}" )).andExpect(status().isBadRequest()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_PROBLEM_JSON)).andExpect(jsonPath("$.status").value(400)).andExpect(jsonPath("$.title").value("Validation failed")).andExpect(jsonPath("$.code").value("VALIDATION_FAILED"));}}
}
