package com.xuhang.mealops.mealplan.domain;

import static org.assertj.core.api.Assertions.*;
import java.time.LocalDate; import java.util.*;
import org.junit.jupiter.api.Test;

class MealPlanTest {
 private final LocalDate d=LocalDate.of(2026,8,5);
 private MealSlot slot(int day, MealType t, MealPlanRecipeSelection s){return new MealSlot(d.plusDays(day),t,s);}
 @Test void scheduleSortsAndCopies(){var input=new ArrayList<>(List.of(slot(1,MealType.DINNER,null),slot(0,MealType.LUNCH,null),slot(0,MealType.BREAKFAST,null)));var s=new MealPlanSchedule(d,d.plusDays(1),input);input.clear();assertThat(s.slots()).extracting(MealSlot::mealType).containsExactly(MealType.BREAKFAST,MealType.LUNCH,MealType.DINNER);assertThatThrownBy(()->s.slots().add(slot(0,MealType.DINNER,null))).isInstanceOf(UnsupportedOperationException.class);}
 @Test void acceptsOneAndThreeDayWindowsAndRejectsFour(){assertThatCode(()->new MealPlanSchedule(d,d,List.of(slot(0,MealType.DINNER,null)))).doesNotThrowAnyException();assertThatCode(()->new MealPlanSchedule(d,d.plusDays(2),List.of(slot(0,MealType.DINNER,null)))).doesNotThrowAnyException();assertThatThrownBy(()->new MealPlanSchedule(d,d.plusDays(3),List.of(slot(0,MealType.DINNER,null)))).isInstanceOf(InvalidMealPlanException.class);}
 @Test void rejectsSlotAfterRangeAndOrdersAllBusinessSlots(){var start=LocalDate.of(2026,8,1);assertThatThrownBy(()->new MealPlanSchedule(start,start.plusDays(1),List.of(new MealSlot(start.plusDays(2),MealType.DINNER,null)))).isInstanceOf(InvalidMealPlanException.class);var s=new MealPlanSchedule(start,start.plusDays(1),List.of(new MealSlot(start.plusDays(1),MealType.DINNER,null),new MealSlot(start,MealType.DINNER,null),new MealSlot(start,MealType.LUNCH,null),new MealSlot(start,MealType.BREAKFAST,null)));assertThat(s.slots()).extracting(MealSlot::date,MealSlot::mealType).containsExactly(org.assertj.core.groups.Tuple.tuple(start,MealType.BREAKFAST),org.assertj.core.groups.Tuple.tuple(start,MealType.LUNCH),org.assertj.core.groups.Tuple.tuple(start,MealType.DINNER),org.assertj.core.groups.Tuple.tuple(start.plusDays(1),MealType.DINNER));}
 @Test void rejectsInvalidRangeAndDuplicates(){assertThatThrownBy(()->new MealPlanSchedule(d,d.minusDays(1),List.of(slot(0,MealType.DINNER,null)))).isInstanceOf(InvalidMealPlanException.class);assertThatThrownBy(()->new MealPlanSchedule(d,d,List.of(slot(0,MealType.DINNER,null),slot(0,MealType.DINNER,null)))).isInstanceOf(InvalidMealPlanException.class);}
 @Test void rejectsNullEmptyAndOutOfRangeSlots(){assertThatThrownBy(()->new MealPlanSchedule(d,d,List.of())).isInstanceOf(InvalidMealPlanException.class);assertThatThrownBy(()->new MealPlanSchedule(d,d,null)).isInstanceOf(InvalidMealPlanException.class);assertThatThrownBy(()->new MealPlanSchedule(d,d,java.util.Arrays.asList((MealSlot)null))).isInstanceOf(InvalidMealPlanException.class);assertThatThrownBy(()->new MealPlanSchedule(d,d,List.of(slot(-1,MealType.DINNER,null)))).isInstanceOf(InvalidMealPlanException.class);assertThatCode(()->new MealPlanSchedule(d,d,List.of(slot(0,MealType.BREAKFAST,null),slot(0,MealType.LUNCH,null)))).doesNotThrowAnyException();}
 @Test void confirmedNeedsAssignments(){var incomplete=new MealPlan(1,MealPlanStatus.DRAFT,new MealPlanSchedule(d,d,List.of(slot(0,MealType.DINNER,null))));assertThatThrownBy(incomplete::confirm).isInstanceOf(InvalidMealPlanException.class);var complete=new MealPlan(1,MealPlanStatus.DRAFT,new MealPlanSchedule(d,d,List.of(slot(0,MealType.DINNER,new MealPlanRecipeSelection(2,1)))));assertThat(complete.confirm().status()).isEqualTo(MealPlanStatus.CONFIRMED);}
 @Test void aggregateStatusInvariants(){var s=new MealPlanSchedule(d,d,List.of(slot(0,MealType.DINNER,null)));assertThatCode(()->new MealPlan(1,MealPlanStatus.CANCELLED,s)).doesNotThrowAnyException();assertThatThrownBy(()->new MealPlan(0,MealPlanStatus.DRAFT,s)).isInstanceOf(InvalidMealPlanException.class);assertThatThrownBy(()->new MealPlan(1,null,s)).isInstanceOf(InvalidMealPlanException.class);assertThatThrownBy(()->new MealPlan(1,MealPlanStatus.DRAFT,null)).isInstanceOf(InvalidMealPlanException.class);}
 @Test void selectionInvariants(){assertThatThrownBy(()->new MealPlanRecipeSelection(0,1)).isInstanceOf(InvalidMealPlanException.class);assertThatThrownBy(()->new MealPlanRecipeSelection(1,0)).isInstanceOf(InvalidMealPlanException.class);}
}
