CREATE TABLE ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    normalized_name TEXT NOT NULL,
    CONSTRAINT pk_ingredient PRIMARY KEY (id),
    CONSTRAINT ck_ingredient_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_ingredient_normalized_name_not_blank CHECK (btrim(normalized_name) <> ''),
    CONSTRAINT uq_ingredient_normalized_name UNIQUE (normalized_name)
);
