CREATE TABLE recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    base_servings INTEGER NOT NULL CONSTRAINT ck_recipe_base_servings_positive CHECK (base_servings > 0),
    estimated_minutes INTEGER NOT NULL CONSTRAINT ck_recipe_estimated_minutes_non_negative CHECK (estimated_minutes >= 0),
    CONSTRAINT ck_recipe_name_nonblank CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ck_recipe_name_length CHECK (char_length(name) <= 100),
    CONSTRAINT pk_recipe PRIMARY KEY (id)
);

CREATE TABLE recipe_ingredient (
    recipe_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    position INTEGER NOT NULL CONSTRAINT ck_recipe_ingredient_position_positive CHECK (position > 0),
    amount NUMERIC NOT NULL CONSTRAINT ck_recipe_ingredient_amount_positive CHECK (amount > 0),
    unit_code VARCHAR(16) NOT NULL CONSTRAINT ck_recipe_ingredient_unit CHECK (unit_code IN ('g', 'ml', 'piece')),
    CONSTRAINT pk_recipe_ingredient PRIMARY KEY (recipe_id, ingredient_id),
    CONSTRAINT uq_recipe_ingredient_position UNIQUE (recipe_id, position),
    CONSTRAINT fk_recipe_ingredient_recipe FOREIGN KEY (recipe_id) REFERENCES recipe(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ingredient_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredient(id)
);

CREATE TABLE recipe_step (
    recipe_id BIGINT NOT NULL,
    position INTEGER NOT NULL CONSTRAINT ck_recipe_step_position_positive CHECK (position > 0),
    instruction TEXT NOT NULL,
    CONSTRAINT pk_recipe_step PRIMARY KEY (recipe_id, position),
    CONSTRAINT ck_recipe_step_nonblank CHECK (char_length(btrim(instruction)) > 0),
    CONSTRAINT ck_recipe_step_length CHECK (char_length(instruction) <= 1000),
    CONSTRAINT fk_recipe_step_recipe FOREIGN KEY (recipe_id) REFERENCES recipe(id) ON DELETE CASCADE
);
