CREATE TABLE inventory_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ingredient_id BIGINT NOT NULL,
    remaining_amount NUMERIC NOT NULL,
    unit_code VARCHAR(16) NOT NULL,
    expires_on DATE NULL,
    CONSTRAINT pk_inventory_batch PRIMARY KEY (id),
    CONSTRAINT fk_inventory_batch_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredient(id),
    CONSTRAINT ck_inventory_batch_remaining_non_negative CHECK (remaining_amount >= 0),
    CONSTRAINT ck_inventory_batch_unit_canonical CHECK (unit_code IN ('g', 'ml', 'piece'))
);
CREATE INDEX idx_inventory_batch_ingredient_expiry ON inventory_batch (ingredient_id, expires_on, id);
