CREATE TABLE meal_plan (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 start_date DATE NOT NULL,
 end_date DATE NOT NULL,
 status VARCHAR(16) NOT NULL,
 CONSTRAINT ck_meal_plan_dates CHECK (start_date <= end_date AND (end_date - start_date) BETWEEN 0 AND 2),
 CONSTRAINT ck_meal_plan_status CHECK (status IN ('DRAFT','CONFIRMED','CANCELLED'))
);
CREATE TABLE meal_plan_slot (
 meal_plan_id BIGINT NOT NULL,
 meal_date DATE NOT NULL,
 meal_type VARCHAR(16) NOT NULL,
 recipe_id BIGINT NULL,
 target_servings INTEGER NULL,
 CONSTRAINT pk_meal_plan_slot PRIMARY KEY (meal_plan_id, meal_date, meal_type),
 CONSTRAINT ck_meal_plan_slot_type CHECK (meal_type IN ('BREAKFAST','LUNCH','DINNER')),
 CONSTRAINT ck_meal_plan_slot_assignment CHECK ((recipe_id IS NULL AND target_servings IS NULL) OR (recipe_id IS NOT NULL AND target_servings IS NOT NULL AND target_servings > 0)),
 CONSTRAINT fk_meal_plan_slot_plan FOREIGN KEY (meal_plan_id) REFERENCES meal_plan(id) ON DELETE CASCADE,
 CONSTRAINT fk_meal_plan_slot_recipe FOREIGN KEY (recipe_id) REFERENCES recipe(id)
);
