package com.xuhang.mealops.mealplan.infrastructure.persistence;

import static org.assertj.core.api.Assertions.*;
import java.time.LocalDate; import java.util.List;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.context.annotation.Import; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.jdbc.core.JdbcTemplate;
import com.xuhang.mealops.mealplan.application.*; import com.xuhang.mealops.mealplan.domain.*; import com.xuhang.mealops.support.PostgresTestConfiguration;

@SpringBootTest @Import(PostgresTestConfiguration.class)
class MealPlanPersistenceIT {
 @Autowired MealPlanRepository repository; @Autowired JdbcTemplate jdbc; private final LocalDate d=LocalDate.of(2026,8,5);
 private long recipe(){return jdbc.queryForObject("INSERT INTO recipe(name,base_servings,estimated_minutes) VALUES ('it-'||clock_timestamp()::text,1,1) RETURNING id",Long.class);}
 private MealPlanSchedule schedule(long r){return new MealPlanSchedule(d,d.plusDays(1),List.of(new MealSlot(d,MealType.DINNER,new MealPlanRecipeSelection(r,1)),new MealSlot(d.plusDays(1),MealType.LUNCH,null)));}
 @Test void createGetOrderingAndReplace(){long r=recipe();var p=repository.create(schedule(r));assertThat(p.status()).isEqualTo(MealPlanStatus.DRAFT);assertThat(p.schedule().slots()).extracting(MealSlot::mealType).containsExactly(MealType.DINNER,MealType.LUNCH);var replaced=repository.replaceDraft(p.id(),new MealPlanSchedule(d,d,List.of(new MealSlot(d,MealType.BREAKFAST,null))));assertThat(replaced.schedule().slots()).hasSize(1).first().extracting(MealSlot::mealType).isEqualTo(MealType.BREAKFAST);}
 @Test void confirmUsesCurrentDatabaseCompletenessAndCancelKeepsRows(){long r=recipe();var p=repository.create(new MealPlanSchedule(d,d,List.of(new MealSlot(d,MealType.DINNER,new MealPlanRecipeSelection(r,1)))));jdbc.update("UPDATE meal_plan_slot SET recipe_id=NULL,target_servings=NULL WHERE meal_plan_id=?",p.id());assertThatThrownBy(()->repository.confirmDraftIfComplete(p.id())).isInstanceOf(MealPlanIncompleteException.class);jdbc.update("UPDATE meal_plan_slot SET recipe_id=?,target_servings=1 WHERE meal_plan_id=?",r,p.id());assertThat(repository.confirmDraftIfComplete(p.id()).status()).isEqualTo(MealPlanStatus.CONFIRMED);assertThat(repository.cancelActive(p.id()).status()).isEqualTo(MealPlanStatus.CANCELLED);assertThat(jdbc.queryForObject("SELECT count(*) FROM meal_plan_slot WHERE meal_plan_id=?",Integer.class,p.id())).isEqualTo(1);}
 @Test void databaseConstraintsRejectInvalidRows(){assertThatThrownBy(()->jdbc.update("INSERT INTO meal_plan(start_date,end_date,status) VALUES ('2026-08-05','2026-08-08','DRAFT')")).isInstanceOf(DataIntegrityViolationException.class);assertThatThrownBy(()->jdbc.update("INSERT INTO meal_plan(start_date,end_date,status) VALUES ('2026-08-05','2026-08-05','ARCHIVED')")).isInstanceOf(DataIntegrityViolationException.class);long id=jdbc.queryForObject("INSERT INTO meal_plan(start_date,end_date,status) VALUES ('2026-08-05','2026-08-05','DRAFT') RETURNING id",Long.class);assertThatThrownBy(()->jdbc.update("INSERT INTO meal_plan_slot(meal_plan_id,meal_date,meal_type,recipe_id,target_servings) VALUES (?, '2026-08-05','BRUNCH',NULL,NULL)",id)).isInstanceOf(DataIntegrityViolationException.class);assertThatThrownBy(()->jdbc.update("INSERT INTO meal_plan_slot(meal_plan_id,meal_date,meal_type,recipe_id,target_servings) VALUES (?, '2026-08-05','DINNER',NULL,1)",id)).isInstanceOf(DataIntegrityViolationException.class);jdbc.update("INSERT INTO meal_plan_slot(meal_plan_id,meal_date,meal_type,recipe_id,target_servings) VALUES (?, '2026-08-05','DINNER',NULL,NULL)",id);assertThatThrownBy(()->jdbc.update("INSERT INTO meal_plan_slot(meal_plan_id,meal_date,meal_type,recipe_id,target_servings) VALUES (?, '2026-08-05','DINNER',NULL,NULL)",id)).isInstanceOf(DataIntegrityViolationException.class);assertThatThrownBy(()->jdbc.update("INSERT INTO meal_plan_slot(meal_plan_id,meal_date,meal_type,recipe_id,target_servings) VALUES (?, '2026-08-05','LUNCH',NULL,-1)",id)).isInstanceOf(DataIntegrityViolationException.class);assertThatThrownBy(()->jdbc.update("INSERT INTO meal_plan_slot(meal_plan_id,meal_date,meal_type,recipe_id,target_servings) VALUES (?, '2026-08-05','BREAKFAST',999999999,1)",id)).isInstanceOf(DataIntegrityViolationException.class);}
 @Test void confirmRequiresAtLeastOneSlot(){long id=jdbc.queryForObject("INSERT INTO meal_plan(start_date,end_date,status) VALUES ('2026-08-05','2026-08-05','DRAFT') RETURNING id",Long.class);assertThatThrownBy(()->repository.confirmDraftIfComplete(id)).isInstanceOf(MealPlanIncompleteException.class);}
 @Test void nonDraftReplaceAndRepeatedCancelPreserveState(){long r=recipe();var p=repository.create(new MealPlanSchedule(d,d,List.of(new MealSlot(d,MealType.DINNER,new MealPlanRecipeSelection(r,1)))));assertThat(repository.confirmDraftIfComplete(p.id()).status()).isEqualTo(MealPlanStatus.CONFIRMED);assertThatThrownBy(()->repository.replaceDraft(p.id(),new MealPlanSchedule(d,d,List.of(new MealSlot(d,MealType.BREAKFAST,null))))).isInstanceOf(MealPlanStateConflictException.class);assertThat(repository.cancelActive(p.id()).status()).isEqualTo(MealPlanStatus.CANCELLED);assertThatThrownBy(()->repository.cancelActive(p.id())).isInstanceOf(MealPlanStateConflictException.class);var still=repository.findById(p.id()).orElseThrow();assertThat(still.status()).isEqualTo(MealPlanStatus.CANCELLED);assertThat(still.schedule().slots()).hasSize(1);}
}
