spring:
  datasource:
    url: jdbc:postgresql://${MEALOPS_DB_HOST:localhost}:${MEALOPS_DB_PORT:55432}/${MEALOPS_DB_NAME:mealops}
    username: ${MEALOPS_DB_USERNAME:mealops}
    password: ${MEALOPS_DB_PASSWORD:mealops}
